# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Exception Name')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Exception detail')),
                ('file_name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='File Name')),
                ('line_number', models.IntegerField(default=0, verbose_name='Error Line Number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Error Created')),
                ('updated', models.DateTimeField(editable=False, verbose_name='Error Updated')),
                ('resolved', models.DateTimeField(editable=False, verbose_name='Error Resolved')),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL, verbose_name='User Created Error')),
            ],
        ),
    ]
